---
title: "Wesley Side Final Stat442"
author: "Wesley Nelson"
date: "`r Sys.Date()`"
output: html_document
---

```{r Packages, message=FALSE, warning=FALSE}

library(dplyr)
library(readr)
library(DataExplorer)
library(cluster)
library(factoextra)

knitr::opts_chunk$set(echo = TRUE)
```





```{r Data/Cleaning, warning=FALSE}

toxins_2023 <- read_csv("C:/Users/wanel/OneDrive/Documents/GitHub/STAT-442-Final-Project/Datasets/2023_us.csv")


toxins_clean <- toxins_2023 %>%
  select(-c(24:29)) %>%
  mutate(`45. METAL CATEGORY` = ifelse(`45. METAL CATEGORY` == "Metal complound categories", "Metal compound categories",`45. METAL CATEGORY` )) 
View(toxins_clean)
  




```

```{r Quick report}

create_report(toxins_2023)


```


```{r Clustering}

toxins_clustered_on_site <- toxins_clean %>%
  select(c(51:65)) %>%
  na.omit()
View(toxins_clustered_on_site)

toxins_clustered_off_site <- toxins_clean %>%
  select(c(66:87)) %>%
  na.omit()
View(toxins_clustered_off_site)



fviz_nbclust(toxins_clustered_on_site, kmeans, method = "wss")
fviz_nbclust(toxins_clustered_on_site, kmeans, method = "gap_stat")
fviz_nbclust(toxins_clustered_on_site, kmeans, method = "silhouette")


# Clusters based on just Off site totals

fviz_nbclust(toxins_clustered_off_site, kmeans, method = "wss")
fviz_nbclust(toxins_clustered_off_site, kmeans, method = "gap_stat")
fviz_nbclust(toxins_clustered_off_site, kmeans, method = "silhouette")

```



